src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

##[UniqueEntity('etudiant')]

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
// #[UniqueEntity(fields: ["etudiant"], message: "Une réservation est déja faite pour ce compte")]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_exam = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $amount = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $transaction_state = null;

    #[ORM\OneToOne(cascade: ['persist'])]
    private ?Etudiant $etudiant = null;

    #[ORM\Column(length: 10)]
    private ?string $type_permis = null;

    #[ORM\Column(type: Types::INTEGER)]
    private ?string $hours = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    private ?Instructeur $instructeurs = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateExam(): ?\DateTimeInterface
    {
        return $this->date_exam;
    }

    public function setDateExam(?\DateTimeInterface $date_exam): static
    {
        $this->date_exam = $date_exam;

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(?string $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getTransactionState(): ?string
    {
        return $this->transaction_state;
    }

    public function setTransactionState(?string $transaction_state): static
    {
        $this->transaction_state = $transaction_state;

        return $this;
    }

    public function getEtudiant(): ?Etudiant
    {
        return $this->etudiant;
    }

    public function setEtudiant(?Etudiant $etudiant): static
    {
        $this->etudiant = $etudiant;

        return $this;
    }

    public function getTypePermis(): ?string
    {
        return $this->type_permis;
    }

    public function setTypePermis(string $type_permis): static
    {
        $this->type_permis = $type_permis;

        return $this;
    }

    public function getHours(): ?string
    {
        return $this->hours;
    }

    public function setHours(string $hours): static
    {
        $this->hours = $hours;

        return $this;
    }

    public function getInstructeurs(): ?Instructeur
    {
        return $this->instructeurs;
    }

    public function setInstructeurs(?Instructeur $instructeurs): static
    {
        $this->instructeurs = $instructeurs;

        return $this;
    }

}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Etudiant;
use App\Entity\Instructeur;
use App\Entity\Reservation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Validator\Constraints\NotBlank;

class ReservationType extends AbstractType
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        // Check the user's role
        $user = $this->security->getUser();
        $isAdmin = $this->security->isGranted('ROLE_ADMIN');

        $builder
            ->add('date_exam', DateType::class, [
                'required' => true,
                'constraints' => [
                    new  NotBlank([
                        'message' => 'Veuillez choisir la Date d\'examen'
                    ])
                ],
                'label'    => 'Date d\'examen',
                'widget' => 'single_text',
                'attr' => ['class' => 'js-datepicker'],
                'html5' => true
            ])
            ->add('hours', IntegerType::class, [
                'label'    => 'Heure de l\'examen',
                'required' => true,
                'attr'     => array(
                    'min'  => 1,
                    'max'  => 23,
                ),
                'constraints' => [
                    new  NotBlank([
                        'message' => 'Veuillez Inserer Heure de l\'examen'
                    ])
                ]
            ])
            ->add('type_permis', ChoiceType::class, [
                'label'    => 'Type de permis',
                'required' => true,
                'multiple' => false,
                'expanded' => true,
                'choices'  => [
                    'Formule (A) : 3300 MAD' => 'Formule A',
                    'Formule (B) : 3550 MAD' => 'Formule B',
                    'Formule (C) : 3800 MAD' => 'Formule C',
                    'Formule (D) : 4050 MAD' => 'Formule D'
                ],
                'constraints' => [
                    new  NotBlank([
                        'message' => 'Veuillez choisir au moins un permis'
                    ])
                ]
            ])

            ->add('instructeurs', EntityType::class, [
                'label'    => 'Instructeur',
                'required' => true,
                // looks for choices from this entity
                'class' => Instructeur::class,
                'placeholder' => 'Choisissez un Instructeur',
                // uses the User.username property as the visible option string
                'choice_label' => 'nom',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez choisir une <b>Instructeur</b>',
                    ])
                ]
            ])
        ;
        if ($isAdmin) {
            // Only add this field if the user is an admin
            $builder
                ->add('etudiant', EntityType::class, [
                    'label'    => 'Etudiant',
                    'required' => true,
                    // looks for choices from this entity
                    'class' => Etudiant::class,
                    'placeholder' => 'Choisissez un Etudiant',
                    // uses the User.username property as the visible option string
                    'choice_label' => 'nom',
                    'constraints' => [
                        new NotBlank([
                            'message' => 'Veuillez choisir une <b>Etudiant</b>',
                        ])
                    ]
                ]);
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Etudiant;
use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Stripe;

#[Route('/reservation')]
class ReservationController extends AbstractController
{
    #[Route('/', name: 'app_reservation_index', methods: ['GET'])]
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_reservation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, AuthorizationCheckerInterface $authorizationChecker): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if($this->isGranted('ROLE_ETUDIANT')) {
                /** @var Etudiant $etudiant */
                $etudiant = $this->getUser()->getEtudiant();
                $reservation->setEtudiant($etudiant);
            }
            $amount = 0;
            switch ($reservation->getTypePermis()) {
                case 'Formule A':
                    $amount = 3300;
                    break;
                case 'Formule B':
                    $amount = 3550;
                    break;
                case 'Formule C':
                    $amount = 3800;
                    break;
                case 'Formule D':
                    $amount = 4050;
                    break;
            }
            $reservation->setAmount($amount);

            $entityManager->persist($reservation);

            try {
                try {
                    Stripe\Stripe::setApiKey($_ENV["STRIPE_SECRET"]);
                    Stripe\Charge::create ([
                            "amount" => $amount * 100,
                            "currency" => "mad",
                            "source" => $request->request->get('stripeToken'),
                            "description" => "Auto école Payment Test : ". $reservation->getTypePermis()
                    ]);
                    $reservation->setTransactionState("SUCCESS");
                    $entityManager->flush();
                    $this->addFlash(
                        'success',
                        'Réservation avec Payment succé'
                    );
                    // $this->addFlash('success', 'Opération réussie');
                } catch (Stripe\Exception\CardException $th) {
                    $this->addFlash(
                        'danger',
                        'Payment refusé  <b>'. $th->getMessage().'</b>'
                    );
                }
            } catch (\Doctrine\DBAL\Exception\UniqueConstraintViolationException $th) {
                if ($authorizationChecker->isGranted('ROLE_ADMIN')) {
                    $this->addFlash('danger', "Une réservation est déja faite pour avec ce compte <b>".$reservation->getEtudiant()->getPrenom().' '.$reservation->getEtudiant()->getNom()).'</b>';
                } else if($authorizationChecker->isGranted('ROLE_ETUDIANT')) {
                    $this->addFlash('danger', "Vous avez dèja effectuer une réservation avec ce compte <b>".$etudiant->getEmail()).'</b>';
                } 
            }


            return $this->redirectToRoute('app_reservation_new', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
            'stripe_key' => $_ENV["STRIPE_KEY"]
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_delete', methods: ['POST'])]
    public function delete(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $reservation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form, {'attr':{'id':'checkout-form'}}) }}

	{% if app.request.hasPreviousSession %}
		{% for label, messages in app.flashes %}
			{% for message in messages %}
				<div class="alert alert-{{ label }}">
					{% if label == 'success' %}
						<i class="fas fa-check"></i> {{ message|raw }}
					{% elseif label == 'danger' %}
						<i class="fal fa-window-close"></i> {{ message|raw }}
					{% endif %}
				</div>
			{% endfor %}
		{% endfor %}
	{% endif %}

	<div class="alert alert-danger d-none" id="errors-message"></div>

	{% set errors = false %}
	
	{% for child in form.children %}
			{% if child.vars.errors is defined and child.vars.errors|length %}
					{% set errors = true %}
			{% endif %}
	{% endfor %}

	{% if errors %}
		{% if not form.vars.valid %}
			<div class="alert alert-warning">
				<div class="d-b m-b-10"><i class="fal fa-times-circle align-middle"></i> Veuillez corriger les erreures suivantes: </div>
				<ul class="p-l-15">
					{# Loop through every form item #}
					{% for child in form.children %}
						{# {{dump(child.vars)}} #}
						{# Display the errors of the form item #}
						{%for error in child.vars.errors%}
							<li class="m-b-5">{{error.message|raw}}</li>
						{%endfor%}
					{%endfor%}
				</ul>
			</div>
		{%endif%}
	{% endif %}


<div class="mb-3">
	<div class="row">
		<div class="col-2">
			<label for="name" class="form-label">{{ form_label(form.hours) }}</label>
		</div>
		<div class="col-3">
			{{ form_widget(form.hours, {'type': 'number','attr': {'class': 'form-control'}}) }}
		</div>
	</div>
</div>
<div class="mb-3">
	<div class="row">
		<div class="col-2">
			<label for="name" class="form-label">{{ form_label(form.date_exam) }}</label>
		</div>
		<div class="col-3">
			{{ form_widget(form.date_exam, {'attr': {'class': 'form-control js-datepicker'}}) }}
		</div>
	</div>
</div>

<div class="mb-3">
	<div class="row">
		<div class="col-2">
			<label for="name" class="form-label">{{ form_label(form.type_permis) }}</label>
		</div>
		<div class="col-3">
			{% for choice in form.type_permis %}
				<div class="form-check">
					{{ form_widget(choice, {'attr': {'class': 'form-check-input'}}) }}
					<label for="name" class="form-label">{{ form_label(choice) }}</label>
				</div>
			{% endfor %}
		</div>
	</div>
</div>

{% if is_granted('ROLE_ADMIN') %}

<div class="mb-3">
	<div class="row">
		<div class="col-2">
			<label for="name" class="form-label">{{ form_label(form.etudiant) }}</label>
		</div>
		<div class="col-3">
			{{ form_widget(form.etudiant, {'attr': {'class': 'form-control'}}) }}
		</div>
	</div>
</div>
{% endif %}

<div class="mb-3">
	<div class="row">
		<div class="col-2">
			<label for="name" class="form-label">{{ form_label(form.instructeurs) }}</label>
		</div>
		<div class="col-3">
			{{ form_widget(form.instructeurs, {'attr': {'class': 'form-control'}}) }}
		</div>
	</div>
</div>

<div class="mb-3">
	<div class="row">
		<div class="col-2">
			<label for="name" class="form-label">Paiement</label>
		</div>
		<div class="col-3">
			<div id="card-element" class="form-control" ></div>
			<input type='hidden' name='stripeToken' id='stripe-token-id'>
		</div>
	</div>
</div>

<button id='pay-btn' class="btn btn-success" name="ajouter" type="submit" onclick="createToken()">{{ button_label|default('Ajouter') }}</button>

<br>
<br>

{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier réservation{% endblock %}

{% block body %}
    <h1 class="mb-3">Modifier réservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('app_reservation_index') }}">Retours à la list</a>
    <br>
    <br>
    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Historique des réservations
{% endblock %}

{% block body %}

	<h1 class="mb-3">Historique des réservations</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Etudiant</th>
				<th>Heure</th>
				<th>Date d'examen</th>
				<th>Montant</th>
				<th>Status de paiement</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for reservation in reservations %}
				<tr>
					<td>{{ reservation.id }}</td>
					<td>
						{% if reservation.etudiant  %}
							{{ reservation.etudiant.nom }}
							{{ reservation.etudiant.prenom }}
						{% else %}
							-
						{% endif %}
					</td>
					<td>{{ reservation.hours }}</td>
					<td>{{ reservation.dateExam ? reservation.dateExam|date('Y-m-d') : '' }}</td>
					<td>{{ reservation.amount | default('-') }}</td>
					<td>
						{% if reservation.transactionState ==  "SUCCESS" %}
							<span class="badge bg-success">
								{{ reservation.transactionState | default('-') }}
							</span>
						{% endif %}
					</td>
					<td>
						<a href="{{ path('app_reservation_show', {'id': reservation.id}) }}" class="btn btn-info">Afficher</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="7">Aucune réservation trouvée</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation
{% endblock %}

{% block body %}

	<h1 class="mb-3">Ajouter une réservation</h1>
    <h4>Payment</h4>

	{{ include('reservation/_form.html.twig') }}

	<a href="{{ path('app_reservation_index') }}">Retours à la liste</a>
{% endblock %}


{% block stylesheets %}
	{{ parent() }}
{% endblock %}

{% block javascripts %}

	{{ parent() }}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

	<script src="https://js.stripe.com/v3/" ></script>
    <script>
        var stripe = Stripe("{{stripe_key}}");
        var elements = stripe.elements();
        var cardElement = elements.create('card', {hidePostalCode: true});
        cardElement.mount('#card-element');
     
        function createToken() {
            document.getElementById("pay-btn").disabled = true;
            stripe.createToken(cardElement).then(function(result) {
                     
                if(typeof result.error != 'undefined') {
                    document.getElementById("pay-btn").disabled = false;
                    $('#errors-message').removeClass('d-none').text(result.error.message);
                }
     
                // Creating Token Success
                if(typeof result.token != 'undefined') {
                    document.getElementById("pay-btn").disabled = false;
                    document.getElementById("stripe-token-id").value = result.token.id;
                    document.getElementById('checkout-form').submit();
                }
            });
        }
    </script>

{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation{% endblock %}

{% block body %}
    <h1>Réservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Etudiant</th>
                <td>{{ reservation.etudiant.nom }} {{ reservation.etudiant.prenom }}</td>
            </tr>
            <tr>
                <th>Instructeur</th>
                <td>{{ reservation.instructeurs.email }}</td>
            </tr>
            <tr>
                <th>Heure</th>
                <td>{{ reservation.hours }}</td>
            </tr>
            <tr>
                <th>Date d'examen</th>
                <td>{{ reservation.dateExam ? reservation.dateExam|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Montant</th>
                <td>{{ reservation.amount }}</td>
            </tr>
            <tr>
                <th>Status de Paiement</th>
                <td>
                    {{ reservation.transactionState|default('Nom Payer') }}
                </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reservation_index') }}">Retour à la liste</a>
    <br>
    <br>
    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}